# Generated by Django 2.1.2 on 2018-11-01 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_instance_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='year',
            field=models.IntegerField(default=2018),
        ),
        migrations.AlterField(
            model_name='takes',
            name='grade',
            field=models.CharField(default='Not Alloted', max_length=20),
        ),
    ]
