# Generated by Django 2.1.2 on 2018-11-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20181101_0812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instance',
            name='instance_id',
        ),
        migrations.AddField(
            model_name='instance',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
