# Generated by Django 2.1.1 on 2018-11-02 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0005_auto_20181101_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qn_id', models.CharField(max_length=20)),
                ('Marks', models.DecimalField(decimal_places=1, max_digits=5)),
                ('full_marks', models.DecimalField(decimal_places=1, max_digits=5)),
                ('pdf', models.CharField(max_length=256)),
                ('page_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.CharField(max_length=20)),
                ('weightage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('instance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Instance')),
            ],
        ),
        migrations.AddField(
            model_name='attempt',
            name='exam_instance_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Exam'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='instance_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Instance'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('instance_id', 'exam_id')},
        ),
    ]
