# Generated by Django 2.1.2 on 2018-11-02 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20181101_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='semester',
            field=models.CharField(choices=[('Autumn', 'Autumn'), ('Spring', 'Spring')], max_length=20),
        ),
        migrations.AlterField(
            model_name='takes',
            name='grade',
            field=models.CharField(choices=[('AA', 'AA'), ('AB', 'AB'), ('BB', 'BB'), ('BC', 'BC'), ('CC', 'CC'), ('CD', 'CD'), ('DD', 'DD'), ('FR', 'FR'), ('DX', 'DX'), ('NA', 'NA')], default='NA', max_length=20),
        ),
    ]
