# Generated by Django 2.1.1 on 2018-11-02 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0006_auto_20181102_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='ta_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ta_id', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attempt',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stud_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
