# Generated by Django 2.1.1 on 2018-11-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20181102_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='attempt_graded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_graded',
            field=models.BooleanField(default=False),
        ),
    ]
