# Generated by Django 2.1.3 on 2018-11-02 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20181102_1328'),
        ('course', '0008_auto_20181102_2029'),
    ]

    operations = [
    ]
