# Generated by Django 2.1.2 on 2018-11-02 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_merge_20181102_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assists',
            old_name='assistant_id',
            new_name='assistant',
        ),
        migrations.RenameField(
            model_name='assists',
            old_name='instance_id',
            new_name='instance',
        ),
        migrations.RenameField(
            model_name='attempt',
            old_name='ta_id',
            new_name='assistant',
        ),
        migrations.RenameField(
            model_name='attempt',
            old_name='exam_instance_id',
            new_name='exam',
        ),
        migrations.RenameField(
            model_name='attempt',
            old_name='instance_id',
            new_name='instance',
        ),
        migrations.RenameField(
            model_name='attempt',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='instance_id',
            new_name='instance',
        ),
        migrations.RenameField(
            model_name='instance',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='takes',
            old_name='instance_id',
            new_name='instance',
        ),
        migrations.RenameField(
            model_name='takes',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='teaches',
            old_name='instance_id',
            new_name='instance',
        ),
        migrations.RenameField(
            model_name='teaches',
            old_name='instructor_id',
            new_name='instructor',
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('instance', 'exam_id')},
        ),
    ]
