# Generated by Django 2.1.3 on 2018-11-02 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20181102_1728'),
        ('course', '0009_merge_20181102_1655'),
    ]

    operations = [
    ]
