# Generated by Django 2.1.1 on 2018-11-02 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_merge_20181102_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='exam_id',
            new_name='exam_name',
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('instance', 'exam_name')},
        ),
    ]
