# Generated by Django 2.1.2 on 2018-11-03 10:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0012_auto_20181103_0147'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assists',
            unique_together={('assistant', 'instance')},
        ),
        migrations.AlterUniqueTogether(
            name='takes',
            unique_together={('instance', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='teaches',
            unique_together={('instructor', 'instance')},
        ),
    ]
