# Generated by Django 2.1.1 on 2018-11-25 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_auto_20181103_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qn_number', models.CharField(max_length=20)),
                ('full_marks', models.DecimalField(decimal_places=1, max_digits=5)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Exam')),
            ],
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='full_marks',
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='instance',
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='qn_id',
        ),
        migrations.AddField(
            model_name='attempt',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.Question'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('exam', 'qn_number')},
        ),
    ]
