# Generated by Django 2.1.1 on 2018-11-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_auto_20181125_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='num_pages',
            field=models.IntegerField(default=1),
        ),
    ]
